versiion: '3.8'

services: 
  db: 
    image: mongo
    contaiiner_name: db
    restart: always
    enviroment: 
      - MONGO_INITDB_ROOT_USERNAME=dio
      - MONGO_INITDB_ROOT_PASSWORD=dio
    ports: 
      - "27017:27017"
    volumes: 
      - D:\Projetos\Projetos Dennis\dio\bootcamp-database-dio\Banco de Dados NOSQL\activities:data/db